### ISSUE TITLE
Selecting JIRA ticket takes you to https://digitransit.atlassian.net/ regardless of search URL

### ISSUE THREAD

**Issue by keirlawson** [samuliheljo/atom-jira-issue-search#1]
This appears to be hard coded so whilst I can search another JIRA it always takes me to a ticket at that URL

**Comment by samuliheljo** [comment]
Hi, sorry it took some time to fix this. This is fixed in 1.0.0.

Note, you have to configure Jira search REST url like this ```https://{host.domain}/```

e.g. https://issues.sonatype.org/
