### ISSUE TITLE
Errors Trying to Search

### ISSUE THREAD

**Issue by program247365** [samuliheljo/atom-jira-issue-search#3]
I get this error when trying to search:

```
errorMessages: ["Field 'summary' does not exist or this field cannot be viewed by anonymous users.",…]
0: "Field 'summary' does not exist or this field cannot be viewed by anonymous users."
1: "Field 'description' does not exist or this field cannot be viewed by anonymous users."
2: "Field 'comment' does not exist or this field cannot be viewed by anonymous users."
```

![screen shot 2016-05-25 at 11 08 53 am](https://cloud.githubusercontent.com/assets/13910/15545119/2b0b7306-2269-11e6-883c-0abf23f5f498.png)

Could be our internal instance of Jira that doesn't allow this. So could be BASIC AUTH or some other auth would need to be implemented for this plugin to work with some instances of Jira: https://developer.atlassian.com/jiradev/jira-apis/jira-rest-apis/jira-rest-api-tutorials/jira-rest-api-example-basic-authentication

**Comment by samuliheljo** [comment]
I quess Jira needs public access in order to search to work.
