### ISSUE TITLE
Error: Error executing search. Ensure that you have configured Jira url correctly.

### ISSUE THREAD

**Issue by nvaken** [samuliheljo/atom-jira-issue-search#5]
Throws errors on our Atlassian JIRA Cloud instance, even though I'm 100% sure the URL checks out. 

```
Error executing search. Ensure that you have configured Jira url correctly. It should be something like: https://xxx.atlassian.net/
```

**Comment by DrChills** [comment]
+1

**Comment by samuliheljo** [comment]
If your Jira requires authentication, it will probably fail like that.

See #4

**Comment by nvaken** [comment]
Ah, that seems to be a legitimate dupe. Though, if this package does only work with anonymous access, I think it would be a good addition to mention so in the readme. This would prevent people from trying out this package in the first place when they're not able to open up JIRA.

**Comment by samuliheljo** [comment]
That's true. Added some info:
https://github.com/samuliheljo/atom-jira-issue-search/commit/beeae7a016b95ea9dedb31b8b117a012632cfa81
